### ISSUE TITLE
Not working with HDT v1.0+

### ISSUE THREAD

**Issue by neonerz** [adnanc/HDT.Plugins.MetaDetector#5]
It seems like with the new version of HDT, MetaDetector doesn't work anymore. Is there any plans to update it?

**Comment by AdnanC** [comment]
I am working on it. It should be up soon.

**Comment by AdnanC** [comment]
I have published the new version. Let me know if you have any issues.

**Comment by neonerz** [comment]
I'm still getting the following error when trying to load it: https://gyazo.com/86bbb98b5f59189b52a68aacdf8a359b

You could see the error, and confirmation that it's running v0.0.7. I'm running HDT version 1.0.3

Just to go over my steps to install.

I disabled MetaDetector in HDT and closed it. Deleted it out of AppData/Roaming/HearthstoneDeckTracker/Plugins. Unblocked the DLL, copied over the MetaDetector folder out of the zip to the plugins folder. Loaded back up HDT, enabled the plugin, and got the error in the screen shot. 

If I then manually acknowledge the error, go back into settings and enable the plugin, I don't get the error and can open the MetaDetector screen, but it never shows the meta decks while playing.

**Comment by AdnanC** [comment]
That is really weird. I tried the same steps and don't get any errors. I have updated the latest release and it shouldn't cause the big HDT error anymore, everything should go into the log file. 

If the window opens and no decks are showing you can try deleting the metaDecks.xml in "%AppData%\HearthstoneDeckTracker\MetaDetector\"

**Comment by sdbds** [comment]
i use it with HDT 1.04 works well。nothing wrong。

**Comment by neonerz** [comment]
Maybe it was just an issue with HDT 1.0.3? Now that I updated to HDT 1.0.4 it seems to be working again.

**Comment by neonerz** [comment]
Actually, I spoke too soon. I'm not getting the error anymore, but the tracker screen is still staying blank. I tried deleting metaDecks.xml from "%AppData%\HearthstoneDeckTracker\MetaDetector\" and it had no effect (it's also worth noting it didn't seem to generate a new one. I played a couple matches to be safe).

Here's a pastebin of the log file from after I upgraded to HDT 1.0.4 and reinstalled MetaDetector: http://pastebin.com/WJZK4rmC - It shows tons of errors.

**Comment by AdnanC** [comment]
can you try deleting metaConfig.xml in the same folder

**Comment by neonerz** [comment]
That did the trick! Tailing the meta_log everything looks great. Thanks for the help.

**Comment by AdnanC** [comment]
good to hear. I have added a check in the code as well now. If any of the config files are missing / corrupt it will try to create a new one.
